from database import db, User, Movie
import bcrypt

MOVIES = [
    {"title": "Inception", "genre": "Sci-Fi, Thriller", "language": "en", "release_year": 2010, "tmdb_rating": 8.8, "poster_url": "https://image.tmdb.org/t/p/w500/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg", "synopsis": "A thief who steals corporate secrets through dream-sharing technology is given the inverse task of planting an idea.", "cast": "Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen Page", "director": "Christopher Nolan", "streaming_platforms": "Netflix, Prime", "mood_tags": "Thriller, Action"},
    {"title": "The Dark Knight", "genre": "Action, Crime, Drama", "language": "en", "release_year": 2008, "tmdb_rating": 9.0, "poster_url": "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg", "synopsis": "When the menace known as the Joker wreaks havoc on Gotham, Batman must accept one of the greatest psychological and physical tests.", "cast": "Christian Bale, Heath Ledger, Aaron Eckhart", "director": "Christopher Nolan", "streaming_platforms": "Netflix, HBO Max", "mood_tags": "Action, Thriller"},
    {"title": "Parasite", "genre": "Drama, Thriller", "language": "ko", "release_year": 2019, "tmdb_rating": 8.6, "poster_url": "https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg", "synopsis": "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.", "cast": "Song Kang-ho, Lee Sun-kyun, Cho Yeo-jeong", "director": "Bong Joon-ho", "streaming_platforms": "Hulu", "mood_tags": "Thriller, Drama"},
    {"title": "The Shawshank Redemption", "genre": "Drama", "language": "en", "release_year": 1994, "tmdb_rating": 9.3, "poster_url": "https://image.tmdb.org/t/p/w500/lyQBXzOQSuE59IsHyhrp0qIiPAz.jpg", "synopsis": "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.", "cast": "Tim Robbins, Morgan Freeman", "director": "Frank Darabont", "streaming_platforms": "Netflix", "mood_tags": "Drama, Sad"},
    {"title": "The Grand Budapest Hotel", "genre": "Comedy, Drama", "language": "en", "release_year": 2014, "tmdb_rating": 8.1, "poster_url": "https://image.tmdb.org/t/p/w500/eWdyYQreja6JGCzqHWXpWHDrrPo.jpg", "synopsis": "The adventures of Gustave H, a legendary concierge at a famous hotel between the wars.", "cast": "Ralph Fiennes, Tony Revolori, Saoirse Ronan", "director": "Wes Anderson", "streaming_platforms": "Disney+", "mood_tags": "Happy, Comedy"},
    {"title": "Interstellar", "genre": "Sci-Fi, Adventure, Drama", "language": "en", "release_year": 2014, "tmdb_rating": 8.6, "poster_url": "https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg", "synopsis": "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.", "cast": "Matthew McConaughey, Anne Hathaway, Jessica Chastain", "director": "Christopher Nolan", "streaming_platforms": "Paramount+", "mood_tags": "Action, Thriller"},
    {"title": "La La Land", "genre": "Romance, Drama, Musical", "language": "en", "release_year": 2016, "tmdb_rating": 8.0, "poster_url": "https://image.tmdb.org/t/p/w500/uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg", "synopsis": "While navigating their careers in Los Angeles, a pianist and an actress fall in love.", "cast": "Ryan Gosling, Emma Stone", "director": "Damien Chazelle", "streaming_platforms": "Netflix, Prime", "mood_tags": "Romantic, Happy"},
    {"title": "Get Out", "genre": "Horror, Thriller", "language": "en", "release_year": 2017, "tmdb_rating": 7.7, "poster_url": "https://image.tmdb.org/t/p/w500/tFXcEccSQMf3lfhfXKSU9iRBpa3.jpg", "synopsis": "A young African-American visits his white girlfriend's parents for the weekend, where his simmering uneasiness proves to be more justified than he foresaw.", "cast": "Daniel Kaluuya, Allison Williams", "director": "Jordan Peele", "streaming_platforms": "Peacock", "mood_tags": "Horror, Thriller"},
    {"title": "Coco", "genre": "Animation, Family, Adventure", "language": "en", "release_year": 2017, "tmdb_rating": 8.4, "poster_url": "https://image.tmdb.org/t/p/w500/gGEsBPAijhVUFoiNpgZXqRVWJt2.jpg", "synopsis": "Aspiring musician Miguel, confronted with his family's ancestral ban on music, enters the Land of the Dead to find his great-great-grandfather.", "cast": "Anthony Gonzalez, Gael García Bernal", "director": "Lee Unkrich", "streaming_platforms": "Disney+", "mood_tags": "Happy, Family"},
    {"title": "Avengers: Endgame", "genre": "Action, Sci-Fi, Adventure", "language": "en", "release_year": 2019, "tmdb_rating": 8.4, "poster_url": "https://image.tmdb.org/t/p/w500/or06FN3Dka5tukK1e9sl16pB3iy.jpg", "synopsis": "After the devastating events of Infinity War, the universe is in ruins. The Avengers assemble once more to reverse Thanos' actions.", "cast": "Robert Downey Jr., Chris Evans, Mark Ruffalo", "director": "Anthony Russo, Joe Russo", "streaming_platforms": "Disney+", "mood_tags": "Action, Happy"},
    {"title": "Whiplash", "genre": "Drama, Music", "language": "en", "release_year": 2014, "tmdb_rating": 8.5, "poster_url": "https://image.tmdb.org/t/p/w500/7fn624j5lj3xTme2SgiLCeuedmO.jpg", "synopsis": "A promising young drummer enrolls at a cutthroat music conservatory where his dreams of greatness are mentored by an instructor who will stop at nothing.", "cast": "Miles Teller, J.K. Simmons", "director": "Damien Chazelle", "streaming_platforms": "Netflix", "mood_tags": "Drama, Thriller"},
    {"title": "Spirited Away", "genre": "Animation, Family, Fantasy", "language": "ja", "release_year": 2001, "tmdb_rating": 8.6, "poster_url": "https://image.tmdb.org/t/p/w500/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg", "synopsis": "During her family's move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits.", "cast": "Daveigh Chase, Suzanne Pleshette", "director": "Hayao Miyazaki", "streaming_platforms": "Netflix", "mood_tags": "Family, Happy"},
    {"title": "Gone Girl", "genre": "Thriller, Drama, Mystery", "language": "en", "release_year": 2014, "tmdb_rating": 8.1, "poster_url": "https://image.tmdb.org/t/p/w500/2liZ2Q0Q9dCCBCO6T6aFVV1zGxV.jpg", "synopsis": "With his wife's disappearance having become the focus of an intense media circus, a man sees the spotlight turned on him when it's suspected that he may not be innocent.", "cast": "Ben Affleck, Rosamund Pike", "director": "David Fincher", "streaming_platforms": "Hulu", "mood_tags": "Thriller, Drama"},
    {"title": "The Notebook", "genre": "Romance, Drama", "language": "en", "release_year": 2004, "tmdb_rating": 7.8, "poster_url": "https://image.tmdb.org/t/p/w500/gMfstesBXKdsHToAUXVPHujUDfb.jpg", "synopsis": "A poor yet passionate young man falls in love with a rich young woman, giving her a sense of freedom, but they are soon separated by her money-hungry parents.", "cast": "Ryan Gosling, Rachel McAdams", "director": "Nick Cassavetes", "streaming_platforms": "Netflix", "mood_tags": "Romantic, Sad"},
    {"title": "The Lion King", "genre": "Animation, Family, Drama", "language": "en", "release_year": 1994, "tmdb_rating": 8.5, "poster_url": "https://image.tmdb.org/t/p/w500/sKCr78MXSLixwmZ8DyJLrpMsd15.jpg", "synopsis": "Lion prince Simba and his father are targeted by his bitter uncle, who wants to ascend the throne himself.", "cast": "Matthew Broderick, Jeremy Irons, James Earl Jones", "director": "Roger Allers, Rob Minkoff", "streaming_platforms": "Disney+", "mood_tags": "Family, Happy"},
    {"title": "Mad Max: Fury Road", "genre": "Action, Sci-Fi, Adventure", "language": "en", "release_year": 2015, "tmdb_rating": 8.1, "poster_url": "https://image.tmdb.org/t/p/w500/8tZYtuWezp8JbcsvHYO0O46tFbo.jpg", "synopsis": "In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler in search for her homeland with the aid of a group of female prisoners.", "cast": "Tom Hardy, Charlize Theron", "director": "George Miller", "streaming_platforms": "HBO Max", "mood_tags": "Action, Thriller"},
    {"title": "Her", "genre": "Romance, Drama, Sci-Fi", "language": "en", "release_year": 2013, "tmdb_rating": 8.0, "poster_url": "https://image.tmdb.org/t/p/w500/lEIaL12hSkqqe83zf0qnFdaFBsv.jpg", "synopsis": "In a near future, a lonely writer develops an unlikely relationship with an operating system designed to meet his every need.", "cast": "Joaquin Phoenix, Scarlett Johansson", "director": "Spike Jonze", "streaming_platforms": "Netflix", "mood_tags": "Romantic, Drama"},
    {"title": "The Conjuring", "genre": "Horror, Thriller", "language": "en", "release_year": 2013, "tmdb_rating": 7.5, "poster_url": "https://image.tmdb.org/t/p/w500/wVYREutTvI2tmxr6ujrHT704wGF.jpg", "synopsis": "Paranormal investigators Ed and Lorraine Warren work to help a family terrorized by a dark presence in their farmhouse.", "cast": "Vera Farmiga, Patrick Wilson", "director": "James Wan", "streaming_platforms": "HBO Max", "mood_tags": "Horror, Thriller"},
    {"title": "Superbad", "genre": "Comedy", "language": "en", "release_year": 2007, "tmdb_rating": 7.6, "poster_url": "https://image.tmdb.org/t/p/w500/ek8e8txUyGLpqJuxNqJzsHOgNZa.jpg", "synopsis": "Two co-dependent high school seniors are forced to deal with separation anxiety after their plan to stage a booze-soaked party goes awry.", "cast": "Jonah Hill, Michael Cera", "director": "Greg Mottola", "streaming_platforms": "Netflix", "mood_tags": "Comedy, Happy"},
    {"title": "Schindler's List", "genre": "Drama, History", "language": "en", "release_year": 1993, "tmdb_rating": 9.0, "poster_url": "https://image.tmdb.org/t/p/w500/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg", "synopsis": "In German-occupied Poland during World War II, Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution.", "cast": "Liam Neeson, Ben Kingsley, Ralph Fiennes", "director": "Steven Spielberg", "streaming_platforms": "Peacock", "mood_tags": "Sad, Drama"},
]

def seed_data():
    if Movie.query.count() > 0:
        return

    admin_exists = User.query.filter_by(email='admin@moviehub.com').first()
    if not admin_exists:
        hashed = bcrypt.hashpw('Admin@123'.encode('utf-8'), bcrypt.gensalt())
        admin = User(name='Admin', email='admin@moviehub.com', password_hash=hashed.decode('utf-8'), is_admin=True)
        db.session.add(admin)

    for m in MOVIES:
        movie = Movie(**m)
        db.session.add(movie)

    db.session.commit()
